(deftheme wheatgrass
  "Created 2017-08-22.")

(custom-theme-set-faces
 'wheatgrass
 '(cursor ((((class color) (min-colors 89)) (:background "thistle"))))
 '(error ((((class color) (min-colors 89)) (:foreground "salmon1"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "orange"))))
 '(success ((((class color) (min-colors 89)) (:foreground "yellow green"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "dark green"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "dark goldenrod"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "SpringGreen4"))))
 '(highlight ((((class color) (min-colors 89)) (:foreground "white" :background "dark green"))))
 '(region ((((class color) (min-colors 89)) (:foreground "white" :background "dark green"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "dark slate gray"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "white" :background "dark goldenrod"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "gray25"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "LightSteelBlue"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "SpringGreen3"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "turquoise"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "pale green"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "white"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "dark khaki"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "aquamarine"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "yellow green"))))
 '(link ((((class color) (min-colors 89)) (:underline t :foreground "cyan"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "dark cyan"))))
 '(default ((t (:background "gray23" :foreground "wheat")))))

(provide-theme 'wheatgrass)
